version: '3.8'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
    env_file:
      .prod.env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run prod
    restart: always

  db:
    image: postgres:11-alpine
    env_file:
      .prod.env
    environment:
      POSTGRES_USER: imp_admin
      POSTGRES_PASSWORD: 49>(bD7V@ws{`-\MzMdX>Y[
      POSTGRES_DB: psitogeg_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres-data:
